"documentation 📖":
  - changed-files:
    - any-glob-to-any-file:
      - README.md
      - docs/**/*

"tooling 🔧":
  - changed-files:
    - any-glob-to-any-file:
      - .github/**/*
      - src/scripts/**/*
      - src/lib/**/*
      - src/hooks/**/*
      - .storybook/**/*

"dependencies 📦":
  - changed-files:
    - any-glob-to-any-file:
      - package.json
      - yarn.lock
      - pnpm-lock.yaml

"config ⚙️":
  - changed-files:
    - any-glob-to-any-file:
      - i18n.config.json
      - next.config.js
      - next-sitemap.config.js
      - tsconfig.json
      - .nvmrc
      - .eslintignore
      - .eslintrc.json
      - .prettierignore
      - .prettierrc
      - netlify.toml

"translation 🌍":
  - changed-files:
    - any-glob-to-any-file:
      - public/content/translations/**/*
      - src/intl/**/*

"content 🖋️":
  - changed-files:
    - any-glob-to-any-file:
      - src/intl/en/**
      - public/content/**/*

"event 📅":
  - changed-files:
    - any-glob-to-any-file:
      - src/data/community-events.json
