name: Get Crowdin Contributors

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  get-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn install

      - name: Get contributors
        env:
          CROWNDOWN_API_KEY: ${{ secrets.CROWNDOWN_API_KEY }}
        run: |
          node scripts/get-contributors.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
